#!/usr/bin/env bash
# -----------------------------------------------------------------------------
# Build the combined frontend+backend image.
# Must run with the build context = the parent dir containing BOTH repos.
# This script figures that out automatically (parent of chimney-deploy/).
#
# Usage:
#   ./build.sh                      # builds chimney-app:local with defaults
#   IMAGE=myname/chimney-app TAG=v1 ./build.sh
#   ./build.sh --build-arg NEXT_PUBLIC_SITE_URL=https://shop.example.com ...
#
# NEXT_PUBLIC_* are baked at build time. For a real deploy, pass your public
# site URL etc. via extra --build-arg flags (see .env.build.example for the list).
# -----------------------------------------------------------------------------
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONTEXT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

IMAGE="${IMAGE:-chimney-app}"
TAG="${TAG:-local}"

# Collect build-args. NEXT_PUBLIC_* are baked into the browser bundle at build
# time, so they MUST be passed here (not at `docker run`). If a .env.build file
# exists next to this script, every KEY=VALUE line is turned into a --build-arg
# automatically, so you keep all frontend build values in one place.
BUILD_ARGS=()
BUILD_ENV_FILE="$SCRIPT_DIR/.env.build"
if [[ -f "$BUILD_ENV_FILE" ]]; then
    echo "Build args    : loading from $BUILD_ENV_FILE"
    while IFS= read -r line; do
        # skip blanks and comments
        [[ -z "${line// }" || "${line#\#}" != "$line" ]] && continue
        BUILD_ARGS+=(--build-arg "$line")
    done < "$BUILD_ENV_FILE"
fi

echo "Build context : $CONTEXT_DIR"
echo "Dockerfile    : $SCRIPT_DIR/Dockerfile"
echo "Image         : ${IMAGE}:${TAG}"
echo

# Docker only reads ONE .dockerignore — from the context root ($CONTEXT_DIR).
# Since we build the two app repos together, generate that root .dockerignore
# by merging each repo's own .dockerignore, prefixing every rule with the repo
# folder so the paths resolve from the context root.
ROOT_IGNORE="$CONTEXT_DIR/.dockerignore"
{
    echo "# AUTO-GENERATED by chimney-deploy/build.sh — do not edit."
    echo "# Merged from each repo's .dockerignore so keys/envs never enter the image."
    for repo in chimney-online-store-backend chimney-online-store-frontend chimney-deploy; do
        f="$CONTEXT_DIR/$repo/.dockerignore"
        [[ -f "$f" ]] || continue
        echo ""
        echo "# ---- $repo ----"
        while IFS= read -r line || [[ -n "$line" ]]; do
            # keep blanks/comments as-is; prefix real rules (incl. negations) with repo/
            if [[ -z "${line// }" || "${line#\#}" != "$line" ]]; then
                echo "$line"
            elif [[ "${line:0:1}" == "!" ]]; then
                echo "!${repo}/${line:1}"
            else
                echo "${repo}/${line}"
            fi
        done < "$f"
    done
    # Always exclude VCS metadata at the root too.
    echo ""
    echo "# ---- root ----"
    echo "**/.git"
} > "$ROOT_IGNORE"
echo "Ignore file   : generated $ROOT_IGNORE"
echo

DOCKERFILE_WIN="$(cygpath -w "$SCRIPT_DIR/Dockerfile" 2>/dev/null || echo "$SCRIPT_DIR/Dockerfile")"
CONTEXT_WIN="$(cygpath -w "$CONTEXT_DIR" 2>/dev/null || echo "$CONTEXT_DIR")"

docker build \
    -f "$DOCKERFILE_WIN" \
    -t "${IMAGE}:${TAG}" \
    "${BUILD_ARGS[@]}" \
    "$@" \
    "$CONTEXT_WIN"

echo
echo "Done. Run one of the scenarios:"
echo "  ./run-local.sh       # app + local DB (fully local)"
echo "  ./run-app-only.sh    # app + remote DB/bucket"
